project 'TestsApp'
workspace '../SGAPI'
platform :ios, '11.0'

target :'TestsApp' do
    pod 'SGAPI', :path => '../'
end

target :'TestsAppTests' do
    pod 'Expecta'
    pod 'SGAPI', :path => '../'
end
